# Generated by Django 2.1.15 on 2020-10-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='iid',
            new_name='item_id',
        ),
    ]
