# Generated by Django 2.1.15 on 2020-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0002_auto_20201009_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
