# Generated by Django 2.1.15 on 2020-10-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_menu', models.CharField(max_length=20)),
                ('ordered_items', models.CharField(max_length=500)),
                ('total_amount', models.CharField(max_length=20)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.Users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
