# Generated by Django 2.1.15 on 2020-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
