# Generated by Django 2.1.15 on 2020-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0005_orders_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='users',
        ),
        migrations.AddField(
            model_name='orders',
            name='contact_no',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
