# Generated by Django 2.1.15 on 2020-10-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0007_auto_20201011_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='unserverd', max_length=10),
        ),
    ]
