# Generated by Django 2.1.15 on 2020-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0008_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(max_length=10),
        ),
    ]
