# Generated by Django 2.1.15 on 2020-10-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0010_auto_20201011_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orders_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordersid',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
