# Generated by Django 2.1.15 on 2020-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0012_auto_20201011_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordersid',
        ),
        migrations.AddField(
            model_name='orders',
            name='identity',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
