# Generated by Django 2.1.15 on 2020-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0013_auto_20201011_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=20)),
                ('prefered_menu', models.CharField(max_length=20)),
                ('ordered_items', models.CharField(max_length=500)),
                ('total_amount', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=20)),
                ('payment_status', models.CharField(default='false', max_length=10)),
                ('order_status', models.CharField(default='unserved', max_length=10)),
            ],
            options={
                'db_table': 'ordered_item',
            },
        ),
    ]
